/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.parser;

import prolixa.node.*;
import prolixa.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTPkgId(@SuppressWarnings("unused") TPkgId node)
    {
        this.index = 0;
    }

    @Override
    public void caseTPackage(@SuppressWarnings("unused") TPackage node)
    {
        this.index = 1;
    }

    @Override
    public void caseTStates(@SuppressWarnings("unused") TStates node)
    {
        this.index = 2;
    }

    @Override
    public void caseTHelpers(@SuppressWarnings("unused") THelpers node)
    {
        this.index = 3;
    }

    @Override
    public void caseTTokens(@SuppressWarnings("unused") TTokens node)
    {
        this.index = 4;
    }

    @Override
    public void caseTIgnored(@SuppressWarnings("unused") TIgnored node)
    {
        this.index = 5;
    }

    @Override
    public void caseTProductions(@SuppressWarnings("unused") TProductions node)
    {
        this.index = 6;
    }

    @Override
    public void caseTTokenSpecifier(@SuppressWarnings("unused") TTokenSpecifier node)
    {
        this.index = 7;
    }

    @Override
    public void caseTProductionSpceifier(@SuppressWarnings("unused") TProductionSpceifier node)
    {
        this.index = 8;
    }

    @Override
    public void caseTThis(@SuppressWarnings("unused") TThis node)
    {
        this.index = 9;
    }

    @Override
    public void caseTIs(@SuppressWarnings("unused") TIs node)
    {
        this.index = 10;
    }

    @Override
    public void caseTProgram(@SuppressWarnings("unused") TProgram node)
    {
        this.index = 11;
    }

    @Override
    public void caseTIt(@SuppressWarnings("unused") TIt node)
    {
        this.index = 12;
    }

    @Override
    public void caseTPresents(@SuppressWarnings("unused") TPresents node)
    {
        this.index = 13;
    }

    @Override
    public void caseTLet(@SuppressWarnings("unused") TLet node)
    {
        this.index = 14;
    }

    @Override
    public void caseTUs(@SuppressWarnings("unused") TUs node)
    {
        this.index = 15;
    }

    @Override
    public void caseTBegin(@SuppressWarnings("unused") TBegin node)
    {
        this.index = 16;
    }

    @Override
    public void caseTWould(@SuppressWarnings("unused") TWould node)
    {
        this.index = 17;
    }

    @Override
    public void caseTBe(@SuppressWarnings("unused") TBe node)
    {
        this.index = 18;
    }

    @Override
    public void caseTAll(@SuppressWarnings("unused") TAll node)
    {
        this.index = 19;
    }

    @Override
    public void caseTUnalterable(@SuppressWarnings("unused") TUnalterable node)
    {
        this.index = 20;
    }

    @Override
    public void caseTAlterable(@SuppressWarnings("unused") TAlterable node)
    {
        this.index = 21;
    }

    @Override
    public void caseTSymbol(@SuppressWarnings("unused") TSymbol node)
    {
        this.index = 22;
    }

    @Override
    public void caseTNumber(@SuppressWarnings("unused") TNumber node)
    {
        this.index = 23;
    }

    @Override
    public void caseTAnswer(@SuppressWarnings("unused") TAnswer node)
    {
        this.index = 24;
    }

    @Override
    public void caseTAnswerValues(@SuppressWarnings("unused") TAnswerValues node)
    {
        this.index = 25;
    }

    @Override
    public void caseTJust(@SuppressWarnings("unused") TJust node)
    {
        this.index = 26;
    }

    @Override
    public void caseTIn(@SuppressWarnings("unused") TIn node)
    {
        this.index = 27;
    }

    @Override
    public void caseTCase(@SuppressWarnings("unused") TCase node)
    {
        this.index = 28;
    }

    @Override
    public void caseTOtherwise(@SuppressWarnings("unused") TOtherwise node)
    {
        this.index = 29;
    }

    @Override
    public void caseTAs1(@SuppressWarnings("unused") TAs1 node)
    {
        this.index = 30;
    }

    @Override
    public void caseTLong(@SuppressWarnings("unused") TLong node)
    {
        this.index = 31;
    }

    @Override
    public void caseTDo(@SuppressWarnings("unused") TDo node)
    {
        this.index = 32;
    }

    @Override
    public void caseTConsidering(@SuppressWarnings("unused") TConsidering node)
    {
        this.index = 33;
    }

    @Override
    public void caseTThat1(@SuppressWarnings("unused") TThat1 node)
    {
        this.index = 34;
    }

    @Override
    public void caseTThat2(@SuppressWarnings("unused") TThat2 node)
    {
        this.index = 35;
    }

    @Override
    public void caseTFrom(@SuppressWarnings("unused") TFrom node)
    {
        this.index = 36;
    }

    @Override
    public void caseTBy(@SuppressWarnings("unused") TBy node)
    {
        this.index = 37;
    }

    @Override
    public void caseTShow(@SuppressWarnings("unused") TShow node)
    {
        this.index = 38;
    }

    @Override
    public void caseTCapture(@SuppressWarnings("unused") TCapture node)
    {
        this.index = 39;
    }

    @Override
    public void caseTAbandon(@SuppressWarnings("unused") TAbandon node)
    {
        this.index = 40;
    }

    @Override
    public void caseTGo(@SuppressWarnings("unused") TGo node)
    {
        this.index = 41;
    }

    @Override
    public void caseTTo(@SuppressWarnings("unused") TTo node)
    {
        this.index = 42;
    }

    @Override
    public void caseTNext(@SuppressWarnings("unused") TNext node)
    {
        this.index = 43;
    }

    @Override
    public void caseTIteration(@SuppressWarnings("unused") TIteration node)
    {
        this.index = 44;
    }

    @Override
    public void caseTVector(@SuppressWarnings("unused") TVector node)
    {
        this.index = 45;
    }

    @Override
    public void caseTOf(@SuppressWarnings("unused") TOf node)
    {
        this.index = 46;
    }

    @Override
    public void caseTX(@SuppressWarnings("unused") TX node)
    {
        this.index = 47;
    }

    @Override
    public void caseTIdentificador(@SuppressWarnings("unused") TIdentificador node)
    {
        this.index = 48;
    }

    @Override
    public void caseTConstante(@SuppressWarnings("unused") TConstante node)
    {
        this.index = 49;
    }

    @Override
    public void caseTVariavel(@SuppressWarnings("unused") TVariavel node)
    {
        this.index = 50;
    }

    @Override
    public void caseTSemicolon(@SuppressWarnings("unused") TSemicolon node)
    {
        this.index = 51;
    }

    @Override
    public void caseTColon(@SuppressWarnings("unused") TColon node)
    {
        this.index = 52;
    }

    @Override
    public void caseTDot(@SuppressWarnings("unused") TDot node)
    {
        this.index = 53;
    }

    @Override
    public void caseTDDot(@SuppressWarnings("unused") TDDot node)
    {
        this.index = 54;
    }

    @Override
    public void caseTAspasSimples(@SuppressWarnings("unused") TAspasSimples node)
    {
        this.index = 55;
    }

    @Override
    public void caseTAspasSimples2(@SuppressWarnings("unused") TAspasSimples2 node)
    {
        this.index = 56;
    }

    @Override
    public void caseTPEsq(@SuppressWarnings("unused") TPEsq node)
    {
        this.index = 57;
    }

    @Override
    public void caseTPDir(@SuppressWarnings("unused") TPDir node)
    {
        this.index = 58;
    }

    @Override
    public void caseTCEsq(@SuppressWarnings("unused") TCEsq node)
    {
        this.index = 59;
    }

    @Override
    public void caseTCDir(@SuppressWarnings("unused") TCDir node)
    {
        this.index = 60;
    }

    @Override
    public void caseTChaveEsq(@SuppressWarnings("unused") TChaveEsq node)
    {
        this.index = 61;
    }

    @Override
    public void caseTChaveDir(@SuppressWarnings("unused") TChaveDir node)
    {
        this.index = 62;
    }

    @Override
    public void caseTSetaDir(@SuppressWarnings("unused") TSetaDir node)
    {
        this.index = 63;
    }

    @Override
    public void caseTBarra(@SuppressWarnings("unused") TBarra node)
    {
        this.index = 64;
    }

    @Override
    public void caseTNumeroHexa(@SuppressWarnings("unused") TNumeroHexa node)
    {
        this.index = 65;
    }

    @Override
    public void caseTQMark(@SuppressWarnings("unused") TQMark node)
    {
        this.index = 66;
    }

    @Override
    public void caseTVincula(@SuppressWarnings("unused") TVincula node)
    {
        this.index = 67;
    }

    @Override
    public void caseTAtribui(@SuppressWarnings("unused") TAtribui node)
    {
        this.index = 68;
    }

    @Override
    public void caseTMais(@SuppressWarnings("unused") TMais node)
    {
        this.index = 69;
    }

    @Override
    public void caseTMenos(@SuppressWarnings("unused") TMenos node)
    {
        this.index = 70;
    }

    @Override
    public void caseTEstrela(@SuppressWarnings("unused") TEstrela node)
    {
        this.index = 71;
    }

    @Override
    public void caseTDiv(@SuppressWarnings("unused") TDiv node)
    {
        this.index = 72;
    }

    @Override
    public void caseTDivInt(@SuppressWarnings("unused") TDivInt node)
    {
        this.index = 73;
    }

    @Override
    public void caseTEq(@SuppressWarnings("unused") TEq node)
    {
        this.index = 74;
    }

    @Override
    public void caseTNeq(@SuppressWarnings("unused") TNeq node)
    {
        this.index = 75;
    }

    @Override
    public void caseTLt(@SuppressWarnings("unused") TLt node)
    {
        this.index = 76;
    }

    @Override
    public void caseTLteq(@SuppressWarnings("unused") TLteq node)
    {
        this.index = 77;
    }

    @Override
    public void caseTGt(@SuppressWarnings("unused") TGt node)
    {
        this.index = 78;
    }

    @Override
    public void caseTGteq(@SuppressWarnings("unused") TGteq node)
    {
        this.index = 79;
    }

    @Override
    public void caseTExclamacao(@SuppressWarnings("unused") TExclamacao node)
    {
        this.index = 80;
    }

    @Override
    public void caseTAnd(@SuppressWarnings("unused") TAnd node)
    {
        this.index = 81;
    }

    @Override
    public void caseTOr(@SuppressWarnings("unused") TOr node)
    {
        this.index = 82;
    }

    @Override
    public void caseTXor(@SuppressWarnings("unused") TXor node)
    {
        this.index = 83;
    }

    @Override
    public void caseTNumero(@SuppressWarnings("unused") TNumero node)
    {
        this.index = 84;
    }

    @Override
    public void caseTString(@SuppressWarnings("unused") TString node)
    {
        this.index = 85;
    }

    @Override
    public void caseTSymbolValues(@SuppressWarnings("unused") TSymbolValues node)
    {
        this.index = 86;
    }

    @Override
    public void caseTChar(@SuppressWarnings("unused") TChar node)
    {
        this.index = 87;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 88;
    }
}
