/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AAAltsTail extends PAAltsTail
{
    private PAAlt _alt_;

    public AAAltsTail()
    {
        // Constructor
    }

    public AAAltsTail(
        @SuppressWarnings("hiding") PAAlt _alt_)
    {
        // Constructor
        setAlt(_alt_);

    }

    @Override
    public Object clone()
    {
        return new AAAltsTail(
            cloneNode(this._alt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAAltsTail(this);
    }

    public PAAlt getAlt()
    {
        return this._alt_;
    }

    public void setAlt(PAAlt node)
    {
        if(this._alt_ != null)
        {
            this._alt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._alt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._alt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._alt_ == child)
        {
            this._alt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._alt_ == oldChild)
        {
            setAlt((PAAlt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
