/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AAAnswerValuesAExp extends PAExp
{
    private TAnswerValues _answerValues_;

    public AAAnswerValuesAExp()
    {
        // Constructor
    }

    public AAAnswerValuesAExp(
        @SuppressWarnings("hiding") TAnswerValues _answerValues_)
    {
        // Constructor
        setAnswerValues(_answerValues_);

    }

    @Override
    public Object clone()
    {
        return new AAAnswerValuesAExp(
            cloneNode(this._answerValues_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAAnswerValuesAExp(this);
    }

    public TAnswerValues getAnswerValues()
    {
        return this._answerValues_;
    }

    public void setAnswerValues(TAnswerValues node)
    {
        if(this._answerValues_ != null)
        {
            this._answerValues_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._answerValues_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._answerValues_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._answerValues_ == child)
        {
            this._answerValues_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._answerValues_ == oldChild)
        {
            setAnswerValues((TAnswerValues) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
