/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AAAtribuicaoAComando extends PAComando
{
    private PAExp _var_;
    private PAExp _exp_;

    public AAAtribuicaoAComando()
    {
        // Constructor
    }

    public AAAtribuicaoAComando(
        @SuppressWarnings("hiding") PAExp _var_,
        @SuppressWarnings("hiding") PAExp _exp_)
    {
        // Constructor
        setVar(_var_);

        setExp(_exp_);

    }

    @Override
    public Object clone()
    {
        return new AAAtribuicaoAComando(
            cloneNode(this._var_),
            cloneNode(this._exp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAAtribuicaoAComando(this);
    }

    public PAExp getVar()
    {
        return this._var_;
    }

    public void setVar(PAExp node)
    {
        if(this._var_ != null)
        {
            this._var_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._var_ = node;
    }

    public PAExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PAExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._var_)
            + toString(this._exp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._var_ == child)
        {
            this._var_ = null;
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._var_ == oldChild)
        {
            setVar((PAExp) newChild);
            return;
        }

        if(this._exp_ == oldChild)
        {
            setExp((PAExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
