/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import java.util.*;
import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AACapturaMatchedAMatchedStmt extends PAMatchedStmt
{
    private final LinkedList<PAExp> _capRest_ = new LinkedList<PAExp>();
    private PAExp _var_;

    public AACapturaMatchedAMatchedStmt()
    {
        // Constructor
    }

    public AACapturaMatchedAMatchedStmt(
        @SuppressWarnings("hiding") List<?> _capRest_,
        @SuppressWarnings("hiding") PAExp _var_)
    {
        // Constructor
        setCapRest(_capRest_);

        setVar(_var_);

    }

    @Override
    public Object clone()
    {
        return new AACapturaMatchedAMatchedStmt(
            cloneList(this._capRest_),
            cloneNode(this._var_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAACapturaMatchedAMatchedStmt(this);
    }

    public LinkedList<PAExp> getCapRest()
    {
        return this._capRest_;
    }

    public void setCapRest(List<?> list)
    {
        for(PAExp e : this._capRest_)
        {
            e.parent(null);
        }
        this._capRest_.clear();

        for(Object obj_e : list)
        {
            PAExp e = (PAExp) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._capRest_.add(e);
        }
    }

    public PAExp getVar()
    {
        return this._var_;
    }

    public void setVar(PAExp node)
    {
        if(this._var_ != null)
        {
            this._var_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._var_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._capRest_)
            + toString(this._var_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._capRest_.remove(child))
        {
            return;
        }

        if(this._var_ == child)
        {
            this._var_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PAExp> i = this._capRest_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAExp) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._var_ == oldChild)
        {
            setVar((PAExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
