/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AACharABasic extends PABasic
{
    private PAChar _char_;

    public AACharABasic()
    {
        // Constructor
    }

    public AACharABasic(
        @SuppressWarnings("hiding") PAChar _char_)
    {
        // Constructor
        setChar(_char_);

    }

    @Override
    public Object clone()
    {
        return new AACharABasic(
            cloneNode(this._char_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAACharABasic(this);
    }

    public PAChar getChar()
    {
        return this._char_;
    }

    public void setChar(PAChar node)
    {
        if(this._char_ != null)
        {
            this._char_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._char_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._char_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._char_ == child)
        {
            this._char_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._char_ == oldChild)
        {
            setChar((PAChar) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
