/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import java.util.*;
import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AAConcat extends PAConcat
{
    private final LinkedList<PAExprUn> _exprs_ = new LinkedList<PAExprUn>();

    public AAConcat()
    {
        // Constructor
    }

    public AAConcat(
        @SuppressWarnings("hiding") List<?> _exprs_)
    {
        // Constructor
        setExprs(_exprs_);

    }

    @Override
    public Object clone()
    {
        return new AAConcat(
            cloneList(this._exprs_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAConcat(this);
    }

    public LinkedList<PAExprUn> getExprs()
    {
        return this._exprs_;
    }

    public void setExprs(List<?> list)
    {
        for(PAExprUn e : this._exprs_)
        {
            e.parent(null);
        }
        this._exprs_.clear();

        for(Object obj_e : list)
        {
            PAExprUn e = (PAExprUn) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._exprs_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exprs_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exprs_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PAExprUn> i = this._exprs_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAExprUn) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
