/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import java.util.*;
import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AAComandos extends PAComandos
{
    private final LinkedList<PAComando> _cmds_ = new LinkedList<PAComando>();

    public AAComandos()
    {
        // Constructor
    }

    public AAComandos(
        @SuppressWarnings("hiding") List<?> _cmds_)
    {
        // Constructor
        setCmds(_cmds_);

    }

    @Override
    public Object clone()
    {
        return new AAComandos(
            cloneList(this._cmds_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAComandos(this);
    }

    public LinkedList<PAComando> getCmds()
    {
        return this._cmds_;
    }

    public void setCmds(List<?> list)
    {
        for(PAComando e : this._cmds_)
        {
            e.parent(null);
        }
        this._cmds_.clear();

        for(Object obj_e : list)
        {
            PAComando e = (PAComando) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._cmds_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._cmds_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._cmds_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PAComando> i = this._cmds_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAComando) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
