/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AAConjuntoABasic extends PABasic
{
    private PAConjunto _conj_;

    public AAConjuntoABasic()
    {
        // Constructor
    }

    public AAConjuntoABasic(
        @SuppressWarnings("hiding") PAConjunto _conj_)
    {
        // Constructor
        setConj(_conj_);

    }

    @Override
    public Object clone()
    {
        return new AAConjuntoABasic(
            cloneNode(this._conj_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAConjuntoABasic(this);
    }

    public PAConjunto getConj()
    {
        return this._conj_;
    }

    public void setConj(PAConjunto node)
    {
        if(this._conj_ != null)
        {
            this._conj_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._conj_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._conj_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._conj_ == child)
        {
            this._conj_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._conj_ == oldChild)
        {
            setConj((PAConjunto) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
