/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AAExprRegTail extends PAExprRegTail
{
    private PAConcat _concat_;

    public AAExprRegTail()
    {
        // Constructor
    }

    public AAExprRegTail(
        @SuppressWarnings("hiding") PAConcat _concat_)
    {
        // Constructor
        setConcat(_concat_);

    }

    @Override
    public Object clone()
    {
        return new AAExprRegTail(
            cloneNode(this._concat_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAExprRegTail(this);
    }

    public PAConcat getConcat()
    {
        return this._concat_;
    }

    public void setConcat(PAConcat node)
    {
        if(this._concat_ != null)
        {
            this._concat_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._concat_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._concat_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._concat_ == child)
        {
            this._concat_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._concat_ == oldChild)
        {
            setConcat((PAConcat) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
