/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AAGrammarAStart extends PAStart
{
    private PAGrammar _gramatica_;

    public AAGrammarAStart()
    {
        // Constructor
    }

    public AAGrammarAStart(
        @SuppressWarnings("hiding") PAGrammar _gramatica_)
    {
        // Constructor
        setGramatica(_gramatica_);

    }

    @Override
    public Object clone()
    {
        return new AAGrammarAStart(
            cloneNode(this._gramatica_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAGrammarAStart(this);
    }

    public PAGrammar getGramatica()
    {
        return this._gramatica_;
    }

    public void setGramatica(PAGrammar node)
    {
        if(this._gramatica_ != null)
        {
            this._gramatica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._gramatica_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._gramatica_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._gramatica_ == child)
        {
            this._gramatica_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._gramatica_ == oldChild)
        {
            setGramatica((PAGrammar) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
