/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AAHexAChar extends PAChar
{
    private TNumeroHexa _numeroHexa_;

    public AAHexAChar()
    {
        // Constructor
    }

    public AAHexAChar(
        @SuppressWarnings("hiding") TNumeroHexa _numeroHexa_)
    {
        // Constructor
        setNumeroHexa(_numeroHexa_);

    }

    @Override
    public Object clone()
    {
        return new AAHexAChar(
            cloneNode(this._numeroHexa_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAHexAChar(this);
    }

    public TNumeroHexa getNumeroHexa()
    {
        return this._numeroHexa_;
    }

    public void setNumeroHexa(TNumeroHexa node)
    {
        if(this._numeroHexa_ != null)
        {
            this._numeroHexa_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._numeroHexa_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._numeroHexa_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._numeroHexa_ == child)
        {
            this._numeroHexa_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._numeroHexa_ == oldChild)
        {
            setNumeroHexa((TNumeroHexa) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
