/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AAHelperDef extends PAHelperDef
{
    private TIdentificador _nome_;
    private PAExprReg _expr_;

    public AAHelperDef()
    {
        // Constructor
    }

    public AAHelperDef(
        @SuppressWarnings("hiding") TIdentificador _nome_,
        @SuppressWarnings("hiding") PAExprReg _expr_)
    {
        // Constructor
        setNome(_nome_);

        setExpr(_expr_);

    }

    @Override
    public Object clone()
    {
        return new AAHelperDef(
            cloneNode(this._nome_),
            cloneNode(this._expr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAHelperDef(this);
    }

    public TIdentificador getNome()
    {
        return this._nome_;
    }

    public void setNome(TIdentificador node)
    {
        if(this._nome_ != null)
        {
            this._nome_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nome_ = node;
    }

    public PAExprReg getExpr()
    {
        return this._expr_;
    }

    public void setExpr(PAExprReg node)
    {
        if(this._expr_ != null)
        {
            this._expr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._nome_)
            + toString(this._expr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._nome_ == child)
        {
            this._nome_ = null;
            return;
        }

        if(this._expr_ == child)
        {
            this._expr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._nome_ == oldChild)
        {
            setNome((TIdentificador) newChild);
            return;
        }

        if(this._expr_ == oldChild)
        {
            setExpr((PAExprReg) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
