/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AAIfComElseMatchedAMatchedStmt extends PAMatchedStmt
{
    private PAExp _exp_;
    private PAMatchedStmt _mtched_;
    private PAMatchedStmt2 _mtched2_;

    public AAIfComElseMatchedAMatchedStmt()
    {
        // Constructor
    }

    public AAIfComElseMatchedAMatchedStmt(
        @SuppressWarnings("hiding") PAExp _exp_,
        @SuppressWarnings("hiding") PAMatchedStmt _mtched_,
        @SuppressWarnings("hiding") PAMatchedStmt2 _mtched2_)
    {
        // Constructor
        setExp(_exp_);

        setMtched(_mtched_);

        setMtched2(_mtched2_);

    }

    @Override
    public Object clone()
    {
        return new AAIfComElseMatchedAMatchedStmt(
            cloneNode(this._exp_),
            cloneNode(this._mtched_),
            cloneNode(this._mtched2_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAIfComElseMatchedAMatchedStmt(this);
    }

    public PAExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PAExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public PAMatchedStmt getMtched()
    {
        return this._mtched_;
    }

    public void setMtched(PAMatchedStmt node)
    {
        if(this._mtched_ != null)
        {
            this._mtched_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mtched_ = node;
    }

    public PAMatchedStmt2 getMtched2()
    {
        return this._mtched2_;
    }

    public void setMtched2(PAMatchedStmt2 node)
    {
        if(this._mtched2_ != null)
        {
            this._mtched2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mtched2_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp_)
            + toString(this._mtched_)
            + toString(this._mtched2_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._mtched_ == child)
        {
            this._mtched_ = null;
            return;
        }

        if(this._mtched2_ == child)
        {
            this._mtched2_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp_ == oldChild)
        {
            setExp((PAExp) newChild);
            return;
        }

        if(this._mtched_ == oldChild)
        {
            setMtched((PAMatchedStmt) newChild);
            return;
        }

        if(this._mtched2_ == oldChild)
        {
            setMtched2((PAMatchedStmt2) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
