/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AAIteracaoAComando extends PAComando
{
    private PAExp _var_;
    private PAExp _inicio_;
    private PAExp _fim_;
    private PAExp _step_;
    private PAComando _cmd_;

    public AAIteracaoAComando()
    {
        // Constructor
    }

    public AAIteracaoAComando(
        @SuppressWarnings("hiding") PAExp _var_,
        @SuppressWarnings("hiding") PAExp _inicio_,
        @SuppressWarnings("hiding") PAExp _fim_,
        @SuppressWarnings("hiding") PAExp _step_,
        @SuppressWarnings("hiding") PAComando _cmd_)
    {
        // Constructor
        setVar(_var_);

        setInicio(_inicio_);

        setFim(_fim_);

        setStep(_step_);

        setCmd(_cmd_);

    }

    @Override
    public Object clone()
    {
        return new AAIteracaoAComando(
            cloneNode(this._var_),
            cloneNode(this._inicio_),
            cloneNode(this._fim_),
            cloneNode(this._step_),
            cloneNode(this._cmd_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAIteracaoAComando(this);
    }

    public PAExp getVar()
    {
        return this._var_;
    }

    public void setVar(PAExp node)
    {
        if(this._var_ != null)
        {
            this._var_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._var_ = node;
    }

    public PAExp getInicio()
    {
        return this._inicio_;
    }

    public void setInicio(PAExp node)
    {
        if(this._inicio_ != null)
        {
            this._inicio_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._inicio_ = node;
    }

    public PAExp getFim()
    {
        return this._fim_;
    }

    public void setFim(PAExp node)
    {
        if(this._fim_ != null)
        {
            this._fim_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fim_ = node;
    }

    public PAExp getStep()
    {
        return this._step_;
    }

    public void setStep(PAExp node)
    {
        if(this._step_ != null)
        {
            this._step_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._step_ = node;
    }

    public PAComando getCmd()
    {
        return this._cmd_;
    }

    public void setCmd(PAComando node)
    {
        if(this._cmd_ != null)
        {
            this._cmd_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cmd_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._var_)
            + toString(this._inicio_)
            + toString(this._fim_)
            + toString(this._step_)
            + toString(this._cmd_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._var_ == child)
        {
            this._var_ = null;
            return;
        }

        if(this._inicio_ == child)
        {
            this._inicio_ = null;
            return;
        }

        if(this._fim_ == child)
        {
            this._fim_ = null;
            return;
        }

        if(this._step_ == child)
        {
            this._step_ = null;
            return;
        }

        if(this._cmd_ == child)
        {
            this._cmd_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._var_ == oldChild)
        {
            setVar((PAExp) newChild);
            return;
        }

        if(this._inicio_ == oldChild)
        {
            setInicio((PAExp) newChild);
            return;
        }

        if(this._fim_ == oldChild)
        {
            setFim((PAExp) newChild);
            return;
        }

        if(this._step_ == oldChild)
        {
            setStep((PAExp) newChild);
            return;
        }

        if(this._cmd_ == oldChild)
        {
            setCmd((PAComando) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
