/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AAMatchedStatementAMatchedStmt2 extends PAMatchedStmt2
{
    private PAMatchedStmt _mtched_;

    public AAMatchedStatementAMatchedStmt2()
    {
        // Constructor
    }

    public AAMatchedStatementAMatchedStmt2(
        @SuppressWarnings("hiding") PAMatchedStmt _mtched_)
    {
        // Constructor
        setMtched(_mtched_);

    }

    @Override
    public Object clone()
    {
        return new AAMatchedStatementAMatchedStmt2(
            cloneNode(this._mtched_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAMatchedStatementAMatchedStmt2(this);
    }

    public PAMatchedStmt getMtched()
    {
        return this._mtched_;
    }

    public void setMtched(PAMatchedStmt node)
    {
        if(this._mtched_ != null)
        {
            this._mtched_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mtched_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._mtched_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._mtched_ == child)
        {
            this._mtched_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._mtched_ == oldChild)
        {
            setMtched((PAMatchedStmt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
