/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import java.util.*;
import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AAPkgName extends PAPkgName
{
    private TPkgId _id_;
    private final LinkedList<PAPkgNameTail> _ids_ = new LinkedList<PAPkgNameTail>();

    public AAPkgName()
    {
        // Constructor
    }

    public AAPkgName(
        @SuppressWarnings("hiding") TPkgId _id_,
        @SuppressWarnings("hiding") List<?> _ids_)
    {
        // Constructor
        setId(_id_);

        setIds(_ids_);

    }

    @Override
    public Object clone()
    {
        return new AAPkgName(
            cloneNode(this._id_),
            cloneList(this._ids_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAPkgName(this);
    }

    public TPkgId getId()
    {
        return this._id_;
    }

    public void setId(TPkgId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public LinkedList<PAPkgNameTail> getIds()
    {
        return this._ids_;
    }

    public void setIds(List<?> list)
    {
        for(PAPkgNameTail e : this._ids_)
        {
            e.parent(null);
        }
        this._ids_.clear();

        for(Object obj_e : list)
        {
            PAPkgNameTail e = (PAPkgNameTail) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._ids_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._ids_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._ids_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TPkgId) newChild);
            return;
        }

        for(ListIterator<PAPkgNameTail> i = this._ids_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAPkgNameTail) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
