/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AAProgramaAStart extends PAStart
{
    private PAPrograma _programa_;

    public AAProgramaAStart()
    {
        // Constructor
    }

    public AAProgramaAStart(
        @SuppressWarnings("hiding") PAPrograma _programa_)
    {
        // Constructor
        setPrograma(_programa_);

    }

    @Override
    public Object clone()
    {
        return new AAProgramaAStart(
            cloneNode(this._programa_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAProgramaAStart(this);
    }

    public PAPrograma getPrograma()
    {
        return this._programa_;
    }

    public void setPrograma(PAPrograma node)
    {
        if(this._programa_ != null)
        {
            this._programa_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._programa_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._programa_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._programa_ == child)
        {
            this._programa_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._programa_ == oldChild)
        {
            setPrograma((PAPrograma) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
