/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AAProd extends PAProd
{
    private TIdentificador _nome_;
    private PAAlts _alts_;

    public AAProd()
    {
        // Constructor
    }

    public AAProd(
        @SuppressWarnings("hiding") TIdentificador _nome_,
        @SuppressWarnings("hiding") PAAlts _alts_)
    {
        // Constructor
        setNome(_nome_);

        setAlts(_alts_);

    }

    @Override
    public Object clone()
    {
        return new AAProd(
            cloneNode(this._nome_),
            cloneNode(this._alts_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAProd(this);
    }

    public TIdentificador getNome()
    {
        return this._nome_;
    }

    public void setNome(TIdentificador node)
    {
        if(this._nome_ != null)
        {
            this._nome_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nome_ = node;
    }

    public PAAlts getAlts()
    {
        return this._alts_;
    }

    public void setAlts(PAAlts node)
    {
        if(this._alts_ != null)
        {
            this._alts_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._alts_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._nome_)
            + toString(this._alts_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._nome_ == child)
        {
            this._nome_ = null;
            return;
        }

        if(this._alts_ == child)
        {
            this._alts_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._nome_ == oldChild)
        {
            setNome((TIdentificador) newChild);
            return;
        }

        if(this._alts_ == oldChild)
        {
            setAlts((PAAlts) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
