/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import java.util.*;
import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AAShowMatchedAMatchedStmt extends PAMatchedStmt
{
    private final LinkedList<PAExp> _showRest_ = new LinkedList<PAExp>();
    private PAExp _exp_;

    public AAShowMatchedAMatchedStmt()
    {
        // Constructor
    }

    public AAShowMatchedAMatchedStmt(
        @SuppressWarnings("hiding") List<?> _showRest_,
        @SuppressWarnings("hiding") PAExp _exp_)
    {
        // Constructor
        setShowRest(_showRest_);

        setExp(_exp_);

    }

    @Override
    public Object clone()
    {
        return new AAShowMatchedAMatchedStmt(
            cloneList(this._showRest_),
            cloneNode(this._exp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAShowMatchedAMatchedStmt(this);
    }

    public LinkedList<PAExp> getShowRest()
    {
        return this._showRest_;
    }

    public void setShowRest(List<?> list)
    {
        for(PAExp e : this._showRest_)
        {
            e.parent(null);
        }
        this._showRest_.clear();

        for(Object obj_e : list)
        {
            PAExp e = (PAExp) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._showRest_.add(e);
        }
    }

    public PAExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PAExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._showRest_)
            + toString(this._exp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._showRest_.remove(child))
        {
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PAExp> i = this._showRest_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAExp) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._exp_ == oldChild)
        {
            setExp((PAExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
