/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AAStateListTail extends PAStateListTail
{
    private TIdentificador _id_;
    private PATransition _trans_;

    public AAStateListTail()
    {
        // Constructor
    }

    public AAStateListTail(
        @SuppressWarnings("hiding") TIdentificador _id_,
        @SuppressWarnings("hiding") PATransition _trans_)
    {
        // Constructor
        setId(_id_);

        setTrans(_trans_);

    }

    @Override
    public Object clone()
    {
        return new AAStateListTail(
            cloneNode(this._id_),
            cloneNode(this._trans_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAStateListTail(this);
    }

    public TIdentificador getId()
    {
        return this._id_;
    }

    public void setId(TIdentificador node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public PATransition getTrans()
    {
        return this._trans_;
    }

    public void setTrans(PATransition node)
    {
        if(this._trans_ != null)
        {
            this._trans_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._trans_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._trans_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._trans_ == child)
        {
            this._trans_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TIdentificador) newChild);
            return;
        }

        if(this._trans_ == oldChild)
        {
            setTrans((PATransition) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
