/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AAStates extends PAStates
{
    private PAIdList _lista_;

    public AAStates()
    {
        // Constructor
    }

    public AAStates(
        @SuppressWarnings("hiding") PAIdList _lista_)
    {
        // Constructor
        setLista(_lista_);

    }

    @Override
    public Object clone()
    {
        return new AAStates(
            cloneNode(this._lista_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAStates(this);
    }

    public PAIdList getLista()
    {
        return this._lista_;
    }

    public void setLista(PAIdList node)
    {
        if(this._lista_ != null)
        {
            this._lista_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lista_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lista_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lista_ == child)
        {
            this._lista_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._lista_ == oldChild)
        {
            setLista((PAIdList) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
