/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AASymbolValuesAExp extends PAExp
{
    private TSymbolValues _symbolValues_;

    public AASymbolValuesAExp()
    {
        // Constructor
    }

    public AASymbolValuesAExp(
        @SuppressWarnings("hiding") TSymbolValues _symbolValues_)
    {
        // Constructor
        setSymbolValues(_symbolValues_);

    }

    @Override
    public Object clone()
    {
        return new AASymbolValuesAExp(
            cloneNode(this._symbolValues_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAASymbolValuesAExp(this);
    }

    public TSymbolValues getSymbolValues()
    {
        return this._symbolValues_;
    }

    public void setSymbolValues(TSymbolValues node)
    {
        if(this._symbolValues_ != null)
        {
            this._symbolValues_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._symbolValues_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._symbolValues_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._symbolValues_ == child)
        {
            this._symbolValues_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._symbolValues_ == oldChild)
        {
            setSymbolValues((TSymbolValues) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
