/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import java.util.*;
import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AATokens extends PATokens
{
    private final LinkedList<PATokenDef> _defs_ = new LinkedList<PATokenDef>();

    public AATokens()
    {
        // Constructor
    }

    public AATokens(
        @SuppressWarnings("hiding") List<?> _defs_)
    {
        // Constructor
        setDefs(_defs_);

    }

    @Override
    public Object clone()
    {
        return new AATokens(
            cloneList(this._defs_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAATokens(this);
    }

    public LinkedList<PATokenDef> getDefs()
    {
        return this._defs_;
    }

    public void setDefs(List<?> list)
    {
        for(PATokenDef e : this._defs_)
        {
            e.parent(null);
        }
        this._defs_.clear();

        for(Object obj_e : list)
        {
            PATokenDef e = (PATokenDef) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._defs_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._defs_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._defs_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PATokenDef> i = this._defs_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PATokenDef) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
