/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AATokenDef extends PATokenDef
{
    private PAStateList _states_;
    private TIdentificador _nome_;
    private PAExprReg _expr_;
    private PALookAhead _look_;

    public AATokenDef()
    {
        // Constructor
    }

    public AATokenDef(
        @SuppressWarnings("hiding") PAStateList _states_,
        @SuppressWarnings("hiding") TIdentificador _nome_,
        @SuppressWarnings("hiding") PAExprReg _expr_,
        @SuppressWarnings("hiding") PALookAhead _look_)
    {
        // Constructor
        setStates(_states_);

        setNome(_nome_);

        setExpr(_expr_);

        setLook(_look_);

    }

    @Override
    public Object clone()
    {
        return new AATokenDef(
            cloneNode(this._states_),
            cloneNode(this._nome_),
            cloneNode(this._expr_),
            cloneNode(this._look_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAATokenDef(this);
    }

    public PAStateList getStates()
    {
        return this._states_;
    }

    public void setStates(PAStateList node)
    {
        if(this._states_ != null)
        {
            this._states_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._states_ = node;
    }

    public TIdentificador getNome()
    {
        return this._nome_;
    }

    public void setNome(TIdentificador node)
    {
        if(this._nome_ != null)
        {
            this._nome_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nome_ = node;
    }

    public PAExprReg getExpr()
    {
        return this._expr_;
    }

    public void setExpr(PAExprReg node)
    {
        if(this._expr_ != null)
        {
            this._expr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr_ = node;
    }

    public PALookAhead getLook()
    {
        return this._look_;
    }

    public void setLook(PALookAhead node)
    {
        if(this._look_ != null)
        {
            this._look_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._look_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._states_)
            + toString(this._nome_)
            + toString(this._expr_)
            + toString(this._look_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._states_ == child)
        {
            this._states_ = null;
            return;
        }

        if(this._nome_ == child)
        {
            this._nome_ = null;
            return;
        }

        if(this._expr_ == child)
        {
            this._expr_ = null;
            return;
        }

        if(this._look_ == child)
        {
            this._look_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._states_ == oldChild)
        {
            setStates((PAStateList) newChild);
            return;
        }

        if(this._nome_ == oldChild)
        {
            setNome((TIdentificador) newChild);
            return;
        }

        if(this._expr_ == oldChild)
        {
            setExpr((PAExprReg) newChild);
            return;
        }

        if(this._look_ == oldChild)
        {
            setLook((PALookAhead) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
