/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AATransition extends PATransition
{
    private TIdentificador _destino_;

    public AATransition()
    {
        // Constructor
    }

    public AATransition(
        @SuppressWarnings("hiding") TIdentificador _destino_)
    {
        // Constructor
        setDestino(_destino_);

    }

    @Override
    public Object clone()
    {
        return new AATransition(
            cloneNode(this._destino_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAATransition(this);
    }

    public TIdentificador getDestino()
    {
        return this._destino_;
    }

    public void setDestino(TIdentificador node)
    {
        if(this._destino_ != null)
        {
            this._destino_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._destino_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._destino_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._destino_ == child)
        {
            this._destino_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._destino_ == oldChild)
        {
            setDestino((TIdentificador) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
