/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AAUnalt extends PAUnalt
{
    private TIdentificador _nome_;

    public AAUnalt()
    {
        // Constructor
    }

    public AAUnalt(
        @SuppressWarnings("hiding") TIdentificador _nome_)
    {
        // Constructor
        setNome(_nome_);

    }

    @Override
    public Object clone()
    {
        return new AAUnalt(
            cloneNode(this._nome_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAUnalt(this);
    }

    public TIdentificador getNome()
    {
        return this._nome_;
    }

    public void setNome(TIdentificador node)
    {
        if(this._nome_ != null)
        {
            this._nome_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nome_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._nome_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._nome_ == child)
        {
            this._nome_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._nome_ == oldChild)
        {
            setNome((TIdentificador) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
