/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AAUnalterableDeclADeclaracao extends PADeclaracao
{
    private PATipo _tipo_;
    private TIdentificador _nome_;
    private PAExp _vValor_;

    public AAUnalterableDeclADeclaracao()
    {
        // Constructor
    }

    public AAUnalterableDeclADeclaracao(
        @SuppressWarnings("hiding") PATipo _tipo_,
        @SuppressWarnings("hiding") TIdentificador _nome_,
        @SuppressWarnings("hiding") PAExp _vValor_)
    {
        // Constructor
        setTipo(_tipo_);

        setNome(_nome_);

        setVValor(_vValor_);

    }

    @Override
    public Object clone()
    {
        return new AAUnalterableDeclADeclaracao(
            cloneNode(this._tipo_),
            cloneNode(this._nome_),
            cloneNode(this._vValor_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAUnalterableDeclADeclaracao(this);
    }

    public PATipo getTipo()
    {
        return this._tipo_;
    }

    public void setTipo(PATipo node)
    {
        if(this._tipo_ != null)
        {
            this._tipo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tipo_ = node;
    }

    public TIdentificador getNome()
    {
        return this._nome_;
    }

    public void setNome(TIdentificador node)
    {
        if(this._nome_ != null)
        {
            this._nome_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nome_ = node;
    }

    public PAExp getVValor()
    {
        return this._vValor_;
    }

    public void setVValor(PAExp node)
    {
        if(this._vValor_ != null)
        {
            this._vValor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._vValor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tipo_)
            + toString(this._nome_)
            + toString(this._vValor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tipo_ == child)
        {
            this._tipo_ = null;
            return;
        }

        if(this._nome_ == child)
        {
            this._nome_ = null;
            return;
        }

        if(this._vValor_ == child)
        {
            this._vValor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tipo_ == oldChild)
        {
            setTipo((PATipo) newChild);
            return;
        }

        if(this._nome_ == oldChild)
        {
            setNome((TIdentificador) newChild);
            return;
        }

        if(this._vValor_ == oldChild)
        {
            setVValor((PAExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
