/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AAVectorSizesAExp extends PAExp
{
    private PAExp _exp_;
    private PAExp _rest_;

    public AAVectorSizesAExp()
    {
        // Constructor
    }

    public AAVectorSizesAExp(
        @SuppressWarnings("hiding") PAExp _exp_,
        @SuppressWarnings("hiding") PAExp _rest_)
    {
        // Constructor
        setExp(_exp_);

        setRest(_rest_);

    }

    @Override
    public Object clone()
    {
        return new AAVectorSizesAExp(
            cloneNode(this._exp_),
            cloneNode(this._rest_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAVectorSizesAExp(this);
    }

    public PAExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PAExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public PAExp getRest()
    {
        return this._rest_;
    }

    public void setRest(PAExp node)
    {
        if(this._rest_ != null)
        {
            this._rest_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rest_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp_)
            + toString(this._rest_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._rest_ == child)
        {
            this._rest_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp_ == oldChild)
        {
            setExp((PAExp) newChild);
            return;
        }

        if(this._rest_ == oldChild)
        {
            setRest((PAExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
