/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AAVinculacaoMatchedAMatchedStmt extends PAMatchedStmt
{
    private PAUnalt _unalt_;
    private PAExp _exp_;

    public AAVinculacaoMatchedAMatchedStmt()
    {
        // Constructor
    }

    public AAVinculacaoMatchedAMatchedStmt(
        @SuppressWarnings("hiding") PAUnalt _unalt_,
        @SuppressWarnings("hiding") PAExp _exp_)
    {
        // Constructor
        setUnalt(_unalt_);

        setExp(_exp_);

    }

    @Override
    public Object clone()
    {
        return new AAVinculacaoMatchedAMatchedStmt(
            cloneNode(this._unalt_),
            cloneNode(this._exp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAVinculacaoMatchedAMatchedStmt(this);
    }

    public PAUnalt getUnalt()
    {
        return this._unalt_;
    }

    public void setUnalt(PAUnalt node)
    {
        if(this._unalt_ != null)
        {
            this._unalt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._unalt_ = node;
    }

    public PAExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PAExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._unalt_)
            + toString(this._exp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._unalt_ == child)
        {
            this._unalt_ = null;
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._unalt_ == oldChild)
        {
            setUnalt((PAUnalt) newChild);
            return;
        }

        if(this._exp_ == oldChild)
        {
            setExp((PAExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
