/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class TAs1 extends Token
{
    public TAs1()
    {
        super.setText("as");
    }

    public TAs1(int line, int pos)
    {
        super.setText("as");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TAs1(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAs1(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TAs1 text.");
    }
}
