/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class TProductionSpceifier extends Token
{
    public TProductionSpceifier()
    {
        super.setText("P");
    }

    public TProductionSpceifier(int line, int pos)
    {
        super.setText("P");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TProductionSpceifier(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTProductionSpceifier(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TProductionSpceifier text.");
    }
}
