/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.lexer;

import java.io.*;
import prolixa.node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.NORMAL;

    private IPushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") final PushbackReader in)
    {
        this.in = new IPushbackReader() {

            private PushbackReader pushbackReader = in;
            
            @Override
            public void unread(int c) throws IOException {
                pushbackReader.unread(c);
            }
            
            @Override
            public int read() throws IOException {
                return pushbackReader.read();
            }
        };
    }
 
    public Lexer(@SuppressWarnings("hiding") IPushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        // int middle = (low + high) / 2;
                        int middle = (low + high) >>> 1;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 1: state = State.PACKAGE; break;
                            }
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.PACKAGE; break;
                            }
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            @SuppressWarnings("hiding") Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            @SuppressWarnings("hiding") Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            @SuppressWarnings("hiding") Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            @SuppressWarnings("hiding") Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            @SuppressWarnings("hiding") Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            @SuppressWarnings("hiding") Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            @SuppressWarnings("hiding") Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            @SuppressWarnings("hiding") Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            @SuppressWarnings("hiding") Token token = new22(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            @SuppressWarnings("hiding") Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            @SuppressWarnings("hiding") Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            @SuppressWarnings("hiding") Token token = new25(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            @SuppressWarnings("hiding") Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            @SuppressWarnings("hiding") Token token = new27(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            @SuppressWarnings("hiding") Token token = new28(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            @SuppressWarnings("hiding") Token token = new29(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            @SuppressWarnings("hiding") Token token = new30(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            @SuppressWarnings("hiding") Token token = new31(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            @SuppressWarnings("hiding") Token token = new32(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            @SuppressWarnings("hiding") Token token = new33(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            @SuppressWarnings("hiding") Token token = new34(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            @SuppressWarnings("hiding") Token token = new35(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 36:
                        {
                            @SuppressWarnings("hiding") Token token = new36(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 37:
                        {
                            @SuppressWarnings("hiding") Token token = new37(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 38:
                        {
                            @SuppressWarnings("hiding") Token token = new38(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 39:
                        {
                            @SuppressWarnings("hiding") Token token = new39(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 40:
                        {
                            @SuppressWarnings("hiding") Token token = new40(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 41:
                        {
                            @SuppressWarnings("hiding") Token token = new41(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 42:
                        {
                            @SuppressWarnings("hiding") Token token = new42(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 43:
                        {
                            @SuppressWarnings("hiding") Token token = new43(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 44:
                        {
                            @SuppressWarnings("hiding") Token token = new44(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 45:
                        {
                            @SuppressWarnings("hiding") Token token = new45(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 46:
                        {
                            @SuppressWarnings("hiding") Token token = new46(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 47:
                        {
                            @SuppressWarnings("hiding") Token token = new47(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 48:
                        {
                            @SuppressWarnings("hiding") Token token = new48(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 49:
                        {
                            @SuppressWarnings("hiding") Token token = new49(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 50:
                        {
                            @SuppressWarnings("hiding") Token token = new50(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 51:
                        {
                            @SuppressWarnings("hiding") Token token = new51(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 52:
                        {
                            @SuppressWarnings("hiding") Token token = new52(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 53:
                        {
                            @SuppressWarnings("hiding") Token token = new53(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 54:
                        {
                            @SuppressWarnings("hiding") Token token = new54(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 55:
                        {
                            @SuppressWarnings("hiding") Token token = new55(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 56:
                        {
                            @SuppressWarnings("hiding") Token token = new56(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 57:
                        {
                            @SuppressWarnings("hiding") Token token = new57(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 58:
                        {
                            @SuppressWarnings("hiding") Token token = new58(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 59:
                        {
                            @SuppressWarnings("hiding") Token token = new59(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 60:
                        {
                            @SuppressWarnings("hiding") Token token = new60(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 61:
                        {
                            @SuppressWarnings("hiding") Token token = new61(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 62:
                        {
                            @SuppressWarnings("hiding") Token token = new62(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 63:
                        {
                            @SuppressWarnings("hiding") Token token = new63(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 64:
                        {
                            @SuppressWarnings("hiding") Token token = new64(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 65:
                        {
                            @SuppressWarnings("hiding") Token token = new65(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 66:
                        {
                            @SuppressWarnings("hiding") Token token = new66(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 67:
                        {
                            @SuppressWarnings("hiding") Token token = new67(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 68:
                        {
                            @SuppressWarnings("hiding") Token token = new68(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 69:
                        {
                            @SuppressWarnings("hiding") Token token = new69(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 70:
                        {
                            @SuppressWarnings("hiding") Token token = new70(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 71:
                        {
                            @SuppressWarnings("hiding") Token token = new71(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 72:
                        {
                            @SuppressWarnings("hiding") Token token = new72(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 73:
                        {
                            @SuppressWarnings("hiding") Token token = new73(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 74:
                        {
                            @SuppressWarnings("hiding") Token token = new74(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 75:
                        {
                            @SuppressWarnings("hiding") Token token = new75(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 76:
                        {
                            @SuppressWarnings("hiding") Token token = new76(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 77:
                        {
                            @SuppressWarnings("hiding") Token token = new77(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 78:
                        {
                            @SuppressWarnings("hiding") Token token = new78(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 79:
                        {
                            @SuppressWarnings("hiding") Token token = new79(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 80:
                        {
                            @SuppressWarnings("hiding") Token token = new80(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 81:
                        {
                            @SuppressWarnings("hiding") Token token = new81(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 82:
                        {
                            @SuppressWarnings("hiding") Token token = new82(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 83:
                        {
                            @SuppressWarnings("hiding") Token token = new83(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 84:
                        {
                            @SuppressWarnings("hiding") Token token = new84(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 85:
                        {
                            @SuppressWarnings("hiding") Token token = new85(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 86:
                        {
                            @SuppressWarnings("hiding") Token token = new86(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 87:
                        {
                            @SuppressWarnings("hiding") Token token = new87(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 88:
                        {
                            @SuppressWarnings("hiding") Token token = new88(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 89:
                        {
                            @SuppressWarnings("hiding") Token token = new89(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            new InvalidToken(this.text.substring(0, 1), start_line + 1, start_pos + 1),
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPkgId(text, line, pos); }
    Token new1(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPackage(line, pos); }
    Token new2(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TStates(line, pos); }
    Token new3(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new THelpers(line, pos); }
    Token new4(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTokens(line, pos); }
    Token new5(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIgnored(line, pos); }
    Token new6(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TProductions(line, pos); }
    Token new7(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTokenSpecifier(line, pos); }
    Token new8(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TProductionSpceifier(line, pos); }
    Token new9(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TThis(line, pos); }
    Token new10(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIs(line, pos); }
    Token new11(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TProgram(line, pos); }
    Token new12(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIt(line, pos); }
    Token new13(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPresents(line, pos); }
    Token new14(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLet(line, pos); }
    Token new15(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TUs(line, pos); }
    Token new16(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBegin(line, pos); }
    Token new17(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TWould(line, pos); }
    Token new18(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBe(line, pos); }
    Token new19(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAll(line, pos); }
    Token new20(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TUnalterable(line, pos); }
    Token new21(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAlterable(line, pos); }
    Token new22(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSymbol(line, pos); }
    Token new23(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNumber(line, pos); }
    Token new24(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAnswer(line, pos); }
    Token new25(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAnswerValues(text, line, pos); }
    Token new26(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TJust(line, pos); }
    Token new27(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIn(line, pos); }
    Token new28(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCase(line, pos); }
    Token new29(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOtherwise(line, pos); }
    Token new30(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAs1(line, pos); }
    Token new31(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLong(line, pos); }
    Token new32(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDo(line, pos); }
    Token new33(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TConsidering(line, pos); }
    Token new34(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TThat1(line, pos); }
    Token new35(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TThat2(line, pos); }
    Token new36(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFrom(line, pos); }
    Token new37(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBy(line, pos); }
    Token new38(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TShow(line, pos); }
    Token new39(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCapture(line, pos); }
    Token new40(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAbandon(line, pos); }
    Token new41(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TGo(line, pos); }
    Token new42(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTo(line, pos); }
    Token new43(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNext(line, pos); }
    Token new44(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIteration(line, pos); }
    Token new45(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVector(line, pos); }
    Token new46(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOf(line, pos); }
    Token new47(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TX(line, pos); }
    Token new48(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIdentificador(text, line, pos); }
    Token new49(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TConstante(text, line, pos); }
    Token new50(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVariavel(text, line, pos); }
    Token new51(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSemicolon(line, pos); }
    Token new52(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TColon(line, pos); }
    Token new53(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDot(line, pos); }
    Token new54(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDDot(line, pos); }
    Token new55(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAspasSimples(text, line, pos); }
    Token new56(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAspasSimples2(text, line, pos); }
    Token new57(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPEsq(line, pos); }
    Token new58(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPDir(line, pos); }
    Token new59(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCEsq(line, pos); }
    Token new60(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCDir(line, pos); }
    Token new61(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TChaveEsq(line, pos); }
    Token new62(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TChaveDir(line, pos); }
    Token new63(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSetaDir(line, pos); }
    Token new64(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBarra(line, pos); }
    Token new65(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNumeroHexa(text, line, pos); }
    Token new66(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TQMark(line, pos); }
    Token new67(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVincula(line, pos); }
    Token new68(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAtribui(line, pos); }
    Token new69(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMais(line, pos); }
    Token new70(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMenos(line, pos); }
    Token new71(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEstrela(line, pos); }
    Token new72(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDiv(line, pos); }
    Token new73(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDivInt(line, pos); }
    Token new74(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEq(line, pos); }
    Token new75(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNeq(line, pos); }
    Token new76(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLt(line, pos); }
    Token new77(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLteq(line, pos); }
    Token new78(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TGt(line, pos); }
    Token new79(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TGteq(line, pos); }
    Token new80(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TExclamacao(line, pos); }
    Token new81(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAnd(line, pos); }
    Token new82(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOr(line, pos); }
    Token new83(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TXor(line, pos); }
    Token new84(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNumero(text, line, pos); }
    Token new85(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TString(text, line, pos); }
    Token new86(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSymbolValues(text, line, pos); }
    Token new87(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TChar(text, line, pos); }
    Token new88(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBlank(text, line, pos); }
    Token new89(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComment(text, line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // NORMAL
            {{9, 9, 1}, {10, 10, 2}, {13, 13, 3}, {32, 32, 4}, {33, 33, 5}, {34, 34, 6}, {39, 39, 7}, {40, 40, 8}, {41, 41, 9}, {42, 42, 10}, {43, 43, 11}, {44, 44, 12}, {45, 45, 13}, {46, 46, 14}, {47, 47, 15}, {48, 48, 16}, {49, 57, 17}, {58, 58, 18}, {59, 59, 19}, {60, 60, 20}, {61, 61, 21}, {62, 62, 22}, {63, 63, 23}, {65, 71, 24}, {72, 72, 25}, {73, 73, 26}, {74, 75, 24}, {76, 76, 27}, {77, 79, 24}, {80, 80, 28}, {81, 82, 24}, {83, 83, 29}, {84, 84, 30}, {85, 90, 24}, {91, 91, 31}, {93, 93, 32}, {97, 97, 33}, {98, 98, 34}, {99, 99, 35}, {100, 100, 36}, {102, 102, 37}, {103, 103, 38}, {105, 105, 39}, {106, 106, 40}, {108, 108, 41}, {110, 110, 42}, {111, 111, 43}, {112, 112, 44}, {115, 115, 45}, {116, 116, 46}, {117, 117, 47}, {118, 118, 48}, {119, 119, 49}, {120, 120, 50}, {121, 121, 51}, {123, 123, 52}, {124, 124, 53}, {125, 125, 54}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {{9, 9, 1}, {10, 10, 55}, {13, 32, -2}, },
            {{9, 32, -2}, },
            {{61, 61, 56}, },
            {{0, 33, 57}, {34, 34, 58}, {35, 38, 57}, {40, 65535, 57}, },
            {{0, 9, 59}, {11, 12, 59}, {14, 65535, 59}, },
            {},
            {},
            {},
            {},
            {},
            {{62, 62, 60}, },
            {},
            {{47, 47, 61}, },
            {{46, 46, 62}, {48, 57, 17}, {88, 88, 63}, {120, 120, 64}, },
            {{46, 57, -18}, },
            {{61, 61, 65}, },
            {},
            {{61, 61, 66}, },
            {{61, 61, 67}, },
            {{61, 61, 68}, },
            {},
            {{65, 90, 69}, {95, 95, 70}, {97, 122, 71}, },
            {{65, 95, -26}, {97, 100, 71}, {101, 101, 72}, {102, 122, 71}, },
            {{65, 95, -26}, {97, 102, 71}, {103, 103, 73}, {104, 115, 71}, {116, 116, 74}, {117, 122, 71}, },
            {{65, 100, -27}, {101, 101, 75}, {102, 122, 71}, },
            {{65, 95, -26}, {97, 97, 76}, {98, 113, 71}, {114, 114, 77}, {115, 122, 71}, },
            {{65, 95, -26}, {97, 115, 71}, {116, 116, 78}, {117, 122, 71}, },
            {{65, 95, -26}, {97, 103, 71}, {104, 104, 79}, {105, 110, 71}, {111, 111, 80}, {112, 122, 71}, },
            {},
            {},
            {{98, 98, 81}, {108, 108, 82}, {110, 110, 83}, {115, 115, 84}, },
            {{101, 101, 85}, {121, 121, 86}, },
            {{97, 97, 87}, {111, 111, 88}, },
            {{111, 111, 89}, },
            {{114, 114, 90}, },
            {{111, 111, 91}, },
            {{110, 110, 92}, {115, 115, 93}, {116, 116, 94}, },
            {{117, 117, 95}, },
            {{111, 111, 96}, },
            {{101, 101, 97}, {111, 111, 98}, {117, 117, 99}, },
            {{102, 102, 100}, {114, 114, 101}, {116, 116, 102}, },
            {{114, 114, 103}, },
            {{104, 104, 104}, {121, 121, 105}, },
            {{104, 104, 106}, {111, 111, 107}, },
            {{110, 110, 108}, {115, 115, 109}, },
            {{101, 101, 110}, },
            {{111, 111, 111}, },
            {{111, 111, 112}, },
            {{101, 101, 113}, },
            {{0, 124, 114}, {125, 125, 115}, {126, 65535, 114}, },
            {},
            {},
            {{9, 32, -2}, },
            {},
            {{0, 65535, -8}, },
            {},
            {{39, 39, 116}, },
            {},
            {},
            {{48, 57, 117}, },
            {{48, 57, 118}, {65, 70, 118}, {97, 102, 118}, },
            {{48, 102, -65}, },
            {},
            {},
            {},
            {},
            {{65, 122, -26}, },
            {{65, 122, -26}, },
            {{65, 122, -26}, },
            {{65, 95, -26}, {97, 107, 71}, {108, 108, 119}, {109, 122, 71}, },
            {{65, 95, -26}, {97, 109, 71}, {110, 110, 120}, {111, 122, 71}, },
            {{65, 122, -26}, },
            {{65, 115, -31}, {116, 116, 121}, {117, 122, 71}, },
            {{65, 95, -26}, {97, 98, 71}, {99, 99, 122}, {100, 122, 71}, },
            {{65, 95, -26}, {97, 110, 71}, {111, 111, 123}, {112, 122, 71}, },
            {{65, 95, -26}, {97, 97, 124}, {98, 122, 71}, },
            {{65, 95, -26}, {97, 97, 125}, {98, 104, 71}, {105, 105, 126}, {106, 122, 71}, },
            {{65, 95, -26}, {97, 106, 71}, {107, 107, 127}, {108, 122, 71}, },
            {{97, 97, 128}, },
            {{108, 108, 129}, {116, 116, 130}, },
            {{100, 100, 131}, {115, 115, 132}, },
            {},
            {{103, 103, 133}, },
            {},
            {{112, 112, 134}, {115, 115, 135}, },
            {{110, 110, 136}, },
            {},
            {{111, 111, 137}, },
            {},
            {},
            {},
            {{101, 101, 138}, },
            {{115, 115, 139}, },
            {{110, 110, 140}, },
            {{120, 120, 141}, },
            {},
            {{109, 109, 142}, },
            {},
            {},
            {{104, 104, 143}, },
            {{101, 101, 144}, {111, 111, 145}, },
            {{111, 111, 146}, },
            {{109, 109, 147}, },
            {{97, 97, 148}, },
            {},
            {{97, 97, 149}, },
            {},
            {{99, 99, 150}, },
            {{117, 117, 151}, },
            {{114, 114, 152}, },
            {{115, 115, 153}, },
            {{0, 65535, -54}, },
            {},
            {},
            {{48, 57, 154}, },
            {{48, 102, -65}, },
            {{65, 95, -26}, {97, 111, 71}, {112, 112, 155}, {113, 122, 71}, },
            {{65, 110, -79}, {111, 111, 156}, {112, 122, 71}, },
            {{65, 122, -26}, },
            {{65, 106, -82}, {107, 107, 157}, {108, 122, 71}, },
            {{65, 95, -26}, {97, 99, 71}, {100, 100, 158}, {101, 122, 71}, },
            {{65, 115, -31}, {116, 116, 159}, {117, 122, 71}, },
            {{65, 115, -31}, {116, 116, 160}, {117, 122, 71}, },
            {{65, 95, -26}, {97, 114, 71}, {115, 115, 161}, {116, 122, 71}, },
            {{65, 100, -27}, {101, 101, 162}, {102, 122, 71}, },
            {{110, 110, 163}, },
            {},
            {{101, 101, 164}, },
            {},
            {{119, 119, 165}, },
            {{105, 105, 166}, },
            {{116, 116, 167}, },
            {{101, 101, 168}, },
            {{115, 115, 169}, },
            {{109, 109, 170}, },
            {{114, 114, 171}, },
            {{116, 116, 172}, },
            {{103, 103, 173}, },
            {{116, 116, 174}, },
            {{98, 98, 175}, },
            {{101, 101, 176}, },
            {{115, 115, 177}, },
            {{103, 103, 178}, },
            {{119, 119, 179}, },
            {{98, 98, 180}, },
            {{116, 116, 181}, },
            {{108, 108, 182}, },
            {{116, 116, 183}, },
            {{108, 108, 184}, },
            {},
            {},
            {{46, 46, 62}, {48, 57, 154}, },
            {{65, 100, -27}, {101, 101, 185}, {102, 122, 71}, },
            {{65, 95, -26}, {97, 113, 71}, {114, 114, 186}, {115, 122, 71}, },
            {{65, 95, -26}, {97, 97, 187}, {98, 122, 71}, },
            {{65, 95, -26}, {97, 116, 71}, {117, 117, 188}, {118, 122, 71}, },
            {{65, 100, -27}, {101, 101, 189}, {102, 122, 71}, },
            {{65, 122, -26}, },
            {{65, 122, -26}, },
            {{65, 109, -75}, {110, 110, 190}, {111, 122, 71}, },
            {{100, 100, 191}, },
            {{114, 114, 192}, },
            {{101, 101, 193}, },
            {{110, 110, 194}, },
            {{117, 117, 195}, },
            {},
            {{105, 105, 196}, },
            {},
            {{97, 97, 197}, },
            {},
            {},
            {},
            {{101, 101, 198}, },
            {{114, 114, 199}, },
            {{101, 101, 200}, },
            {{114, 114, 201}, },
            {},
            {{111, 111, 202}, },
            {},
            {{116, 116, 203}, },
            {{111, 111, 204}, },
            {{100, 100, 205}, },
            {{65, 113, -158}, {114, 114, 206}, {115, 122, 71}, },
            {{65, 100, -27}, {101, 101, 207}, {102, 122, 71}, },
            {{65, 102, -28}, {103, 103, 208}, {104, 122, 71}, },
            {{65, 98, -78}, {99, 99, 209}, {100, 122, 71}, },
            {{65, 114, -128}, {115, 115, 210}, {116, 122, 71}, },
            {{65, 114, -128}, {115, 115, 211}, {116, 122, 71}, },
            {{111, 111, 212}, },
            {{97, 97, 213}, },
            {{114, 114, 214}, },
            {},
            {{114, 114, 215}, },
            {{100, 100, 216}, },
            {{116, 116, 217}, },
            {{114, 114, 218}, },
            {{119, 119, 219}, },
            {{110, 110, 220}, },
            {{97, 97, 221}, },
            {{108, 108, 222}, },
            {{101, 101, 223}, },
            {{114, 114, 224}, },
            {},
            {{65, 114, -128}, {115, 115, 225}, {116, 122, 71}, },
            {{65, 99, -125}, {100, 100, 226}, {101, 122, 71}, },
            {{65, 100, -27}, {101, 101, 227}, {102, 122, 71}, },
            {{65, 115, -31}, {116, 116, 228}, {117, 122, 71}, },
            {{65, 122, -26}, },
            {{65, 122, -26}, },
            {{110, 110, 229}, },
            {{98, 98, 230}, },
            {},
            {{101, 101, 231}, },
            {{101, 101, 232}, },
            {{105, 105, 233}, },
            {},
            {{105, 105, 234}, },
            {{116, 116, 235}, },
            {{109, 109, 236}, },
            {},
            {{114, 114, 237}, },
            {},
            {{65, 122, -26}, },
            {{65, 122, -26}, },
            {{65, 122, -26}, },
            {{65, 95, -26}, {97, 104, 71}, {105, 105, 238}, {106, 122, 71}, },
            {},
            {{108, 108, 239}, },
            {},
            {{114, 114, 240}, },
            {{111, 111, 241}, },
            {{115, 115, 242}, },
            {{115, 115, 243}, },
            {},
            {{97, 97, 244}, },
            {{65, 110, -79}, {111, 111, 245}, {112, 122, 71}, },
            {{101, 101, 246}, },
            {{105, 105, 247}, },
            {{110, 110, 248}, },
            {{101, 101, 249}, },
            {},
            {{98, 98, 250}, },
            {{65, 109, -75}, {110, 110, 251}, {111, 122, 71}, },
            {{65, 90, 252}, },
            {{110, 110, 253}, },
            {},
            {},
            {{108, 108, 254}, },
            {{65, 114, -128}, {115, 115, 255}, {116, 122, 71}, },
            {{65, 90, 256}, {95, 95, 257}, {97, 122, 258}, },
            {{103, 103, 259}, },
            {{101, 101, 260}, },
            {{65, 122, -26}, },
            {{65, 122, -254}, },
            {{65, 122, -254}, },
            {{65, 122, -254}, },
            {},
            {{65, 90, 261}, },
            {{65, 90, 262}, {95, 95, 263}, {97, 122, 264}, },
            {{65, 122, -263}, },
            {{65, 122, -263}, },
            {{65, 122, -263}, },
        }
        { // PACKAGE
            {{9, 9, 1}, {10, 10, 2}, {13, 13, 3}, {32, 32, 4}, {33, 33, 5}, {34, 34, 6}, {39, 39, 7}, {40, 40, 8}, {41, 41, 9}, {42, 42, 10}, {43, 43, 11}, {44, 44, 12}, {45, 45, 13}, {46, 46, 14}, {47, 47, 15}, {48, 48, 16}, {49, 57, 17}, {58, 58, 18}, {59, 59, 19}, {60, 60, 20}, {61, 61, 21}, {62, 62, 22}, {63, 63, 23}, {65, 71, 24}, {72, 72, 25}, {73, 73, 26}, {74, 75, 24}, {76, 76, 27}, {77, 79, 24}, {80, 80, 28}, {81, 82, 24}, {83, 83, 29}, {84, 84, 30}, {85, 90, 24}, {91, 91, 31}, {93, 93, 32}, {95, 95, 33}, {97, 97, 34}, {98, 98, 35}, {99, 99, 36}, {100, 100, 37}, {101, 101, 38}, {102, 102, 39}, {103, 103, 40}, {104, 104, 38}, {105, 105, 41}, {106, 106, 42}, {107, 107, 38}, {108, 108, 43}, {109, 109, 38}, {110, 110, 44}, {111, 111, 45}, {112, 112, 46}, {113, 114, 38}, {115, 115, 47}, {116, 116, 48}, {117, 117, 49}, {118, 118, 50}, {119, 119, 51}, {120, 120, 52}, {121, 121, 53}, {122, 122, 38}, {123, 123, 54}, {124, 124, 55}, {125, 125, 56}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {{9, 9, 1}, {10, 10, 57}, {13, 32, -2}, },
            {{9, 32, -2}, },
            {{61, 61, 58}, },
            {{0, 33, 59}, {34, 34, 60}, {35, 38, 59}, {40, 65535, 59}, },
            {{0, 9, 61}, {11, 12, 61}, {14, 65535, 61}, },
            {},
            {},
            {},
            {},
            {},
            {{62, 62, 62}, },
            {},
            {{47, 47, 63}, },
            {{46, 46, 64}, {48, 57, 17}, {88, 88, 65}, {120, 120, 66}, },
            {{46, 57, -18}, },
            {{61, 61, 67}, },
            {},
            {{61, 61, 68}, },
            {{61, 61, 69}, },
            {{61, 61, 70}, },
            {},
            {{48, 57, 71}, {65, 90, 72}, {95, 95, 73}, {97, 122, 74}, },
            {{48, 95, -26}, {97, 100, 74}, {101, 101, 75}, {102, 122, 74}, },
            {{48, 95, -26}, {97, 102, 74}, {103, 103, 76}, {104, 115, 74}, {116, 116, 77}, {117, 122, 74}, },
            {{48, 100, -27}, {101, 101, 78}, {102, 122, 74}, },
            {{48, 95, -26}, {97, 113, 74}, {114, 114, 79}, {115, 122, 74}, },
            {{48, 95, -26}, {97, 115, 74}, {116, 116, 80}, {117, 122, 74}, },
            {{48, 95, -26}, {97, 103, 74}, {104, 104, 81}, {105, 110, 74}, {111, 111, 82}, {112, 122, 74}, },
            {},
            {},
            {{48, 57, 71}, {65, 90, 83}, {95, 95, 84}, {97, 122, 85}, },
            {{48, 95, -35}, {97, 97, 85}, {98, 98, 86}, {99, 107, 85}, {108, 108, 87}, {109, 109, 85}, {110, 110, 88}, {111, 114, 85}, {115, 115, 89}, {116, 122, 85}, },
            {{48, 95, -35}, {97, 100, 85}, {101, 101, 90}, {102, 120, 85}, {121, 121, 91}, {122, 122, 85}, },
            {{48, 95, -35}, {97, 97, 92}, {98, 110, 85}, {111, 111, 93}, {112, 122, 85}, },
            {{48, 95, -35}, {97, 110, 85}, {111, 111, 94}, {112, 122, 85}, },
            {{48, 122, -35}, },
            {{48, 95, -35}, {97, 113, 85}, {114, 114, 95}, {115, 122, 85}, },
            {{48, 110, -39}, {111, 111, 96}, {112, 122, 85}, },
            {{48, 95, -35}, {97, 109, 85}, {110, 110, 97}, {111, 114, 85}, {115, 115, 98}, {116, 116, 99}, {117, 122, 85}, },
            {{48, 95, -35}, {97, 116, 85}, {117, 117, 100}, {118, 122, 85}, },
            {{48, 110, -39}, {111, 111, 101}, {112, 122, 85}, },
            {{48, 100, -37}, {101, 101, 102}, {102, 110, 85}, {111, 111, 103}, {112, 116, 85}, {117, 117, 104}, {118, 122, 85}, },
            {{48, 95, -35}, {97, 101, 85}, {102, 102, 105}, {103, 113, 85}, {114, 114, 106}, {115, 115, 85}, {116, 116, 107}, {117, 122, 85}, },
            {{48, 113, -41}, {114, 114, 108}, {115, 122, 85}, },
            {{48, 95, -35}, {97, 103, 85}, {104, 104, 109}, {105, 120, 85}, {121, 121, 110}, {122, 122, 85}, },
            {{48, 103, -49}, {104, 104, 111}, {105, 110, 85}, {111, 111, 112}, {112, 122, 85}, },
            {{48, 109, -43}, {110, 110, 113}, {111, 114, 85}, {115, 115, 114}, {116, 122, 85}, },
            {{48, 100, -37}, {101, 101, 115}, {102, 122, 85}, },
            {{48, 110, -39}, {111, 111, 116}, {112, 122, 85}, },
            {{48, 110, -39}, {111, 111, 117}, {112, 122, 85}, },
            {{48, 100, -37}, {101, 101, 118}, {102, 122, 85}, },
            {{0, 124, 119}, {125, 125, 120}, {126, 65535, 119}, },
            {},
            {},
            {{9, 32, -2}, },
            {},
            {{0, 65535, -8}, },
            {},
            {{39, 39, 121}, },
            {},
            {},
            {{48, 57, 122}, },
            {{48, 57, 123}, {65, 70, 123}, {97, 102, 123}, },
            {{48, 102, -67}, },
            {},
            {},
            {},
            {},
            {{48, 122, -35}, },
            {{48, 122, -26}, },
            {{48, 122, -26}, },
            {{48, 122, -26}, },
            {{48, 95, -26}, {97, 107, 74}, {108, 108, 124}, {109, 122, 74}, },
            {{48, 95, -26}, {97, 109, 74}, {110, 110, 125}, {111, 122, 74}, },
            {{48, 122, -26}, },
            {{48, 115, -31}, {116, 116, 126}, {117, 122, 74}, },
            {{48, 95, -26}, {97, 110, 74}, {111, 111, 127}, {112, 122, 74}, },
            {{48, 95, -26}, {97, 97, 128}, {98, 122, 74}, },
            {{48, 95, -26}, {97, 97, 129}, {98, 104, 74}, {105, 105, 130}, {106, 122, 74}, },
            {{48, 95, -26}, {97, 106, 74}, {107, 107, 131}, {108, 122, 74}, },
            {{48, 122, -35}, },
            {{48, 122, -35}, },
            {{48, 122, -35}, },
            {{48, 95, -35}, {97, 97, 132}, {98, 122, 85}, },
            {{48, 95, -35}, {97, 107, 85}, {108, 108, 133}, {109, 115, 85}, {116, 116, 134}, {117, 122, 85}, },
            {{48, 95, -35}, {97, 99, 85}, {100, 100, 135}, {101, 114, 85}, {115, 115, 136}, {116, 122, 85}, },
            {{48, 122, -35}, },
            {{48, 95, -35}, {97, 102, 85}, {103, 103, 137}, {104, 122, 85}, },
            {{48, 122, -35}, },
            {{48, 95, -35}, {97, 111, 85}, {112, 112, 138}, {113, 114, 85}, {115, 115, 139}, {116, 122, 85}, },
            {{48, 109, -43}, {110, 110, 140}, {111, 122, 85}, },
            {{48, 122, -35}, },
            {{48, 110, -39}, {111, 111, 141}, {112, 122, 85}, },
            {{48, 122, -35}, },
            {{48, 122, -35}, },
            {{48, 122, -35}, },
            {{48, 100, -37}, {101, 101, 142}, {102, 122, 85}, },
            {{48, 95, -35}, {97, 114, 85}, {115, 115, 143}, {116, 122, 85}, },
            {{48, 109, -43}, {110, 110, 144}, {111, 122, 85}, },
            {{48, 95, -35}, {97, 119, 85}, {120, 120, 145}, {121, 122, 85}, },
            {{48, 122, -35}, },
            {{48, 95, -35}, {97, 108, 85}, {109, 109, 146}, {110, 122, 85}, },
            {{48, 122, -35}, },
            {{48, 122, -35}, },
            {{48, 103, -49}, {104, 104, 147}, {105, 122, 85}, },
            {{48, 100, -37}, {101, 101, 148}, {102, 110, 85}, {111, 111, 149}, {112, 122, 85}, },
            {{48, 110, -39}, {111, 111, 150}, {112, 122, 85}, },
            {{48, 108, -106}, {109, 109, 151}, {110, 122, 85}, },
            {{48, 95, -35}, {97, 97, 152}, {98, 122, 85}, },
            {{48, 122, -35}, },
            {{48, 95, -35}, {97, 97, 153}, {98, 122, 85}, },
            {{48, 122, -35}, },
            {{48, 95, -35}, {97, 98, 85}, {99, 99, 154}, {100, 122, 85}, },
            {{48, 116, -44}, {117, 117, 155}, {118, 122, 85}, },
            {{48, 113, -41}, {114, 114, 156}, {115, 122, 85}, },
            {{48, 114, -102}, {115, 115, 157}, {116, 122, 85}, },
            {{0, 65535, -56}, },
            {},
            {},
            {{48, 57, 158}, },
            {{48, 102, -67}, },
            {{48, 95, -26}, {97, 111, 74}, {112, 112, 159}, {113, 122, 74}, },
            {{48, 110, -81}, {111, 111, 160}, {112, 122, 74}, },
            {{48, 122, -26}, },
            {{48, 95, -26}, {97, 99, 74}, {100, 100, 161}, {101, 122, 74}, },
            {{48, 115, -31}, {116, 116, 162}, {117, 122, 74}, },
            {{48, 115, -31}, {116, 116, 163}, {117, 122, 74}, },
            {{48, 95, -26}, {97, 114, 74}, {115, 115, 164}, {116, 122, 74}, },
            {{48, 100, -27}, {101, 101, 165}, {102, 122, 74}, },
            {{48, 109, -43}, {110, 110, 166}, {111, 122, 85}, },
            {{48, 122, -35}, },
            {{48, 100, -37}, {101, 101, 167}, {102, 122, 85}, },
            {{48, 122, -35}, },
            {{48, 95, -35}, {97, 118, 85}, {119, 119, 168}, {120, 122, 85}, },
            {{48, 95, -35}, {97, 104, 85}, {105, 105, 169}, {106, 122, 85}, },
            {{48, 95, -35}, {97, 115, 85}, {116, 116, 170}, {117, 122, 85}, },
            {{48, 100, -37}, {101, 101, 171}, {102, 122, 85}, },
            {{48, 114, -102}, {115, 115, 172}, {116, 122, 85}, },
            {{48, 108, -106}, {109, 109, 173}, {110, 122, 85}, },
            {{48, 113, -41}, {114, 114, 174}, {115, 122, 85}, },
            {{48, 115, -140}, {116, 116, 175}, {117, 122, 85}, },
            {{48, 102, -92}, {103, 103, 176}, {104, 122, 85}, },
            {{48, 115, -140}, {116, 116, 177}, {117, 122, 85}, },
            {{48, 97, -36}, {98, 98, 178}, {99, 122, 85}, },
            {{48, 100, -37}, {101, 101, 179}, {102, 122, 85}, },
            {{48, 114, -102}, {115, 115, 180}, {116, 122, 85}, },
            {{48, 102, -92}, {103, 103, 181}, {104, 122, 85}, },
            {{48, 118, -138}, {119, 119, 182}, {120, 122, 85}, },
            {{48, 97, -36}, {98, 98, 183}, {99, 122, 85}, },
            {{48, 115, -140}, {116, 116, 184}, {117, 122, 85}, },
            {{48, 107, -89}, {108, 108, 185}, {109, 122, 85}, },
            {{48, 115, -140}, {116, 116, 186}, {117, 122, 85}, },
            {{48, 107, -89}, {108, 108, 187}, {109, 122, 85}, },
            {{48, 122, -35}, },
            {{48, 122, -35}, },
            {{46, 46, 64}, {48, 57, 158}, },
            {{48, 100, -27}, {101, 101, 188}, {102, 122, 74}, },
            {{48, 113, -30}, {114, 114, 189}, {115, 122, 74}, },
            {{48, 95, -26}, {97, 116, 74}, {117, 117, 190}, {118, 122, 74}, },
            {{48, 100, -27}, {101, 101, 191}, {102, 122, 74}, },
            {{48, 122, -26}, },
            {{48, 122, -26}, },
            {{48, 109, -78}, {110, 110, 192}, {111, 122, 74}, },
            {{48, 99, -90}, {100, 100, 193}, {101, 122, 85}, },
            {{48, 113, -41}, {114, 114, 194}, {115, 122, 85}, },
            {{48, 100, -37}, {101, 101, 195}, {102, 122, 85}, },
            {{48, 109, -43}, {110, 110, 196}, {111, 122, 85}, },
            {{48, 116, -44}, {117, 117, 197}, {118, 122, 85}, },
            {{48, 122, -35}, },
            {{48, 104, -139}, {105, 105, 198}, {106, 122, 85}, },
            {{48, 122, -35}, },
            {{48, 95, -35}, {97, 97, 199}, {98, 122, 85}, },
            {{48, 122, -35}, },
            {{48, 122, -35}, },
            {{48, 122, -35}, },
            {{48, 100, -37}, {101, 101, 200}, {102, 122, 85}, },
            {{48, 113, -41}, {114, 114, 201}, {115, 122, 85}, },
            {{48, 100, -37}, {101, 101, 202}, {102, 122, 85}, },
            {{48, 113, -41}, {114, 114, 203}, {115, 122, 85}, },
            {{48, 122, -35}, },
            {{48, 110, -39}, {111, 111, 204}, {112, 122, 85}, },
            {{48, 122, -35}, },
            {{48, 115, -140}, {116, 116, 205}, {117, 122, 85}, },
            {{48, 110, -39}, {111, 111, 206}, {112, 122, 85}, },
            {{48, 99, -90}, {100, 100, 207}, {101, 122, 85}, },
            {{48, 113, -30}, {114, 114, 208}, {115, 122, 74}, },
            {{48, 100, -27}, {101, 101, 209}, {102, 122, 74}, },
            {{48, 95, -26}, {97, 98, 74}, {99, 99, 210}, {100, 122, 74}, },
            {{48, 114, -132}, {115, 115, 211}, {116, 122, 74}, },
            {{48, 114, -132}, {115, 115, 212}, {116, 122, 74}, },
            {{48, 110, -39}, {111, 111, 213}, {112, 122, 85}, },
            {{48, 95, -35}, {97, 97, 214}, {98, 122, 85}, },
            {{48, 113, -41}, {114, 114, 215}, {115, 122, 85}, },
            {{48, 122, -35}, },
            {{48, 113, -41}, {114, 114, 216}, {115, 122, 85}, },
            {{48, 99, -90}, {100, 100, 217}, {101, 122, 85}, },
            {{48, 115, -140}, {116, 116, 218}, {117, 122, 85}, },
            {{48, 113, -41}, {114, 114, 219}, {115, 122, 85}, },
            {{48, 118, -138}, {119, 119, 220}, {120, 122, 85}, },
            {{48, 109, -43}, {110, 110, 221}, {111, 122, 85}, },
            {{48, 95, -35}, {97, 97, 222}, {98, 122, 85}, },
            {{48, 107, -89}, {108, 108, 223}, {109, 122, 85}, },
            {{48, 100, -37}, {101, 101, 224}, {102, 122, 85}, },
            {{48, 113, -41}, {114, 114, 225}, {115, 122, 85}, },
            {{48, 122, -35}, },
            {{48, 114, -132}, {115, 115, 226}, {116, 122, 74}, },
            {{48, 99, -129}, {100, 100, 227}, {101, 122, 74}, },
            {{48, 115, -31}, {116, 116, 228}, {117, 122, 74}, },
            {{48, 122, -26}, },
            {{48, 122, -26}, },
            {{48, 109, -43}, {110, 110, 229}, {111, 122, 85}, },
            {{48, 97, -36}, {98, 98, 230}, {99, 122, 85}, },
            {{48, 122, -35}, },
            {{48, 100, -37}, {101, 101, 231}, {102, 122, 85}, },
            {{48, 100, -37}, {101, 101, 232}, {102, 122, 85}, },
            {{48, 104, -139}, {105, 105, 233}, {106, 122, 85}, },
            {{48, 122, -35}, },
            {{48, 104, -139}, {105, 105, 234}, {106, 122, 85}, },
            {{48, 115, -140}, {116, 116, 235}, {117, 122, 85}, },
            {{48, 108, -106}, {109, 109, 236}, {110, 122, 85}, },
            {{48, 122, -35}, },
            {{48, 113, -41}, {114, 114, 237}, {115, 122, 85}, },
            {{48, 122, -35}, },
            {{48, 122, -26}, },
            {{48, 122, -26}, },
            {{48, 95, -26}, {97, 104, 74}, {105, 105, 238}, {106, 122, 74}, },
            {{48, 122, -35}, },
            {{48, 107, -89}, {108, 108, 239}, {109, 122, 85}, },
            {{48, 122, -35}, },
            {{48, 113, -41}, {114, 114, 240}, {115, 122, 85}, },
            {{48, 110, -39}, {111, 111, 241}, {112, 122, 85}, },
            {{48, 114, -102}, {115, 115, 242}, {116, 122, 85}, },
            {{48, 114, -102}, {115, 115, 243}, {116, 122, 85}, },
            {{48, 122, -35}, },
            {{48, 95, -35}, {97, 97, 244}, {98, 122, 85}, },
            {{48, 110, -81}, {111, 111, 245}, {112, 122, 74}, },
            {{48, 100, -37}, {101, 101, 246}, {102, 122, 85}, },
            {{48, 104, -139}, {105, 105, 247}, {106, 122, 85}, },
            {{48, 109, -43}, {110, 110, 248}, {111, 122, 85}, },
            {{48, 100, -37}, {101, 101, 249}, {102, 122, 85}, },
            {{48, 122, -35}, },
            {{48, 97, -36}, {98, 98, 250}, {99, 122, 85}, },
            {{48, 109, -78}, {110, 110, 251}, {111, 122, 74}, },
            {{48, 57, 71}, {65, 90, 252}, {95, 122, -35}, },
            {{48, 109, -43}, {110, 110, 253}, {111, 122, 85}, },
            {{48, 122, -35}, },
            {{48, 122, -35}, },
            {{48, 107, -89}, {108, 108, 254}, {109, 122, 85}, },
            {{48, 114, -132}, {115, 115, 255}, {116, 122, 74}, },
            {{48, 57, 71}, {65, 90, 256}, {95, 95, 257}, {97, 122, 258}, },
            {{48, 102, -92}, {103, 103, 259}, {104, 122, 85}, },
            {{48, 100, -37}, {101, 101, 260}, {102, 122, 85}, },
            {{48, 122, -26}, },
            {{48, 122, -254}, },
            {{48, 122, -254}, },
            {{48, 122, -254}, },
            {{48, 122, -35}, },
            {{48, 57, 71}, {65, 90, 261}, {95, 122, -35}, },
            {{48, 57, 71}, {65, 90, 262}, {95, 95, 263}, {97, 122, 264}, },
            {{48, 122, -263}, },
            {{48, 122, -263}, },
            {{48, 122, -263}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // NORMAL
        {-1, 88, 88, 88, 88, 80, -1, 55, 57, 58, 71, 69, 52, 70, 53, 72, 84, 84, 54, 51, 76, 67, 78, 66, 48, 48, 48, 48, 8, 48, 7, 59, 60, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 47, -1, 61, 64, 62, 88, 75, -1, 85, -1, 63, 73, -1, -1, -1, 68, 77, 74, 79, 48, 48, 48, 48, 48, 12, 48, 48, 48, 48, 48, 48, -1, -1, -1, 30, 18, 37, -1, -1, 32, -1, 41, 27, 10, -1, -1, -1, -1, 25, -1, 46, 82, -1, -1, -1, -1, -1, 42, -1, 15, -1, -1, -1, -1, -1, 89, 86, 84, 65, 48, 48, 14, 48, 48, 48, 48, 48, 48, -1, 19, -1, 81, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 83, 25, 84, 48, 48, 48, 48, 48, 35, 9, 48, -1, -1, -1, -1, -1, 28, -1, 36, -1, 26, 31, 43, -1, -1, -1, -1, 38, -1, 34, -1, -1, -1, 48, 48, 48, 48, 48, 48, -1, -1, -1, 16, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 17, 48, 48, 48, 48, 2, 4, -1, -1, 24, -1, -1, -1, 23, -1, -1, -1, 22, -1, 45, 3, 5, 1, 48, 40, -1, 39, -1, -1, -1, -1, 11, -1, 48, -1, -1, -1, -1, 13, -1, 48, 21, -1, 44, 29, -1, 48, 50, -1, -1, 6, 50, 50, 50, 33, 20, 49, 49, 49, 49, },
        // PACKAGE
        {-1, 88, 88, 88, 88, 80, -1, 55, 57, 58, 71, 69, 52, 70, 53, 72, 84, 84, 54, 51, 76, 67, 78, 66, 0, 0, 0, 0, 0, 0, 0, 59, 60, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 61, 64, 62, 88, 75, -1, 85, -1, 63, 73, -1, -1, -1, 68, 77, 74, 79, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 89, 86, 84, 65, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 84, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, },

    };*/

    public static class State
    {
        public final static State NORMAL = new State(0);
        public final static State PACKAGE = new State(1);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
